# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 176c48a79df0d90662796cd0815c5a2f68bdffae013842d3a7fcc5f4dca9b576e03651c8145131384c26797d9916205f0675e3186315404b7e0d9c52a3bed129

test:
  secret_key_base: 3e24ad170093a7fdf37fd8c32da4fc7e56abf28bc5eedcf71f3cce23498531f3e0bebe0ba509131d0a81dc4ab919c4cdf930e8f89d5d50106db307f200487af2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
